// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5tJ3ZQqXDFrBuM3Jy7yAf-unZzpgLSlg',
    appId: '1:23468039820:web:cab946b3ee95c2955725a9',
    messagingSenderId: '23468039820',
    projectId: 'bmi-calculator-ccaa9',
    authDomain: 'bmi-calculator-ccaa9.firebaseapp.com',
    storageBucket: 'bmi-calculator-ccaa9.firebasestorage.app',
    measurementId: 'G-J33BPR2BJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtK7t8qT0qdMKQ3EXJvR9Gp9PQMT2nbew',
    appId: '1:23468039820:android:6d8b44113c873f885725a9',
    messagingSenderId: '23468039820',
    projectId: 'bmi-calculator-ccaa9',
    storageBucket: 'bmi-calculator-ccaa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeOSuZaNq6SSzkghv-0LfrVID0oXKOVY',
    appId: '1:23468039820:ios:c5ac9e37e045d2ce5725a9',
    messagingSenderId: '23468039820',
    projectId: 'bmi-calculator-ccaa9',
    storageBucket: 'bmi-calculator-ccaa9.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeOSuZaNq6SSzkghv-0LfrVID0oXKOVY',
    appId: '1:23468039820:ios:c5ac9e37e045d2ce5725a9',
    messagingSenderId: '23468039820',
    projectId: 'bmi-calculator-ccaa9',
    storageBucket: 'bmi-calculator-ccaa9.firebasestorage.app',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5tJ3ZQqXDFrBuM3Jy7yAf-unZzpgLSlg',
    appId: '1:23468039820:web:166b676973f96a255725a9',
    messagingSenderId: '23468039820',
    projectId: 'bmi-calculator-ccaa9',
    authDomain: 'bmi-calculator-ccaa9.firebaseapp.com',
    storageBucket: 'bmi-calculator-ccaa9.firebasestorage.app',
    measurementId: 'G-C9N59LJC4R',
  );
}
